name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'

      - name: Install ReportGenerator tool
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests with coverage
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage"

      - name: Find latest coverage file
        run: |
          testResultsDir=$(System.DefaultWorkingDirectory)/TestResults
          coverageFiles=$(find $testResultsDir -name 'coverage.cobertura.xml')
          if [ -z "$coverageFiles" ]; then
            echo 'Coverage file not found.'
            exit 1
          fi
          reportInput=$(ls -t $coverageFiles | head -n1)

      - name: Generate HTML report
        run: |
          reportOutput=$(System.DefaultWorkingDirectory)/Reports
          reportgenerator "-reports:$reportInput" "-targetdir:$reportOutput" "-reporttypes:HTML"

      - name: Move directories
        run: |
          mv $(System.DefaultWorkingDirectory)/TestResults $(System.DefaultWorkingDirectory)/destination
          mv $(System.DefaultWorkingDirectory)/Reports $(System.DefaultWorkingDirectory)/destination

      - name: Uninstall ReportGenerator tool
        run: dotnet tool uninstall -g dotnet-reportgenerator-globaltool

      - name: Open report in browser
        run: |
          indexFile=$(System.DefaultWorkingDirectory)/destination/Reports/index.html
          if [ -f "$indexFile" ]; then
            echo 'Opening report in browser...'
            xdg-open file://$indexFile
          else
            echo "File $indexFile not found."
          fi
