name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'

      - name: Install ReportGenerator tool globally
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool --version 5.3.7
          if [ $? -ne 0 ]; then
            echo "Failed to install dotnet-reportgenerator-globaltool"
            exit 1
          fi

      - name: Build project
        run: dotnet build --configuration Release $(find . -name ProjetoDeTeste.csproj)

      - name: Run tests with coverage
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" $(find . -name ProjetoDeTeste.csproj)

      - name: Find latest coverage file
        id: find-coverage-file
        run: |
          testResultsDir=$(find . -name ProjetoDeTeste.csproj -printf "%h\n")/TestResults
          echo "Listing contents of TestResults directory:"
          ls -R $testResultsDir
          coverageFiles=$(find $testResultsDir -name 'coverage.cobertura.xml')
          if [ -z "$coverageFiles" ]; then
            echo 'Coverage file not found.'
            exit 1
          fi
          reportInput=$(ls -t $coverageFiles | head -n1)
          echo "::set-output name=reportInput::$reportInput"
          echo "Latest coverage file found: $reportInput"

      - name: Generate HTML report
        run: |
          reportInput=${{ steps.find-coverage-file.outputs.reportInput }}
          reportOutput=$(find . -name ProjetoDeTeste.csproj -printf "%h\n")/Reports
          ~/.dotnet/tools/reportgenerator "-reports:$reportInput" "-targetdir:$reportOutput" "-reporttypes:HTML"

      - name: Uninstall ReportGenerator tool
        run: dotnet tool uninstall -g dotnet-reportgenerator-globaltool

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: |
            $(find . -name ProjetoDeTeste.csproj -printf "%h\n")/Reports
